### ISSUE TITLE
Interactive buttons getting bigger.

### ISSUE THREAD

**Issue by kkkkkmp** [flathub/org.gtk.Gtk3theme.Breeze#100] opened 2023-04-06 12:13 UTC
Issue/odd behavior after update flatpak package.
Close, minimize and maximize buttons are huge.

flathub
![image_2023-04-06_12-51-23](https://user-images.githubusercontent.com/130060848/230378490-b75223fa-dbb9-430a-b3ca-c221c59e9054.png)
BEFORE
 ![image_2023-04-06_12-51-23 (2)](https://user-images.githubusercontent.com/130060848/230378566-d480d652-98d6-46cc-995b-f3372a6c59a8.png)
AFTER 
![image_2023-04-06_12-51-23 (3)](https://user-images.githubusercontent.com/130060848/230378597-726b9ef0-e4ab-4769-b089-611574c1508f.png)

**Comment by doubled1** [comment] 2023-04-07 00:07
I noticed the large window buttons in CSD apps - Ymuse and Remmina both seem affected.

I can confirm they were not big, I upgraded the Breeze GTK3 flatpak, and they became big.

**Comment by vulongm** [comment] 2023-04-07 02:35
Looks like some changes were made in v5.27.4 to the window control. Not sure if the issue also occurs outside flatpak apps, Fedora seems to be on v5.27.3 so can't reproduce it yet. https://invent.kde.org/plasma/breeze-gtk/-/compare/v5.27.3...v5.27.4?from_project_id=1494&straight=false

**Comment by kkkkkmp** [comment] 2023-04-07 11:34
It's not only flathub issue. It getting appears in system applications too on 5.27.4 
![image](https://user-images.githubusercontent.com/130060848/230601170-c08ec728-675a-404e-ad8b-5db4040fc25a.png)
Probable it's fault of ~77 line 18px changed to 24px here 
`src/gtk3/widgets/_window_decorations.scss`
https://invent.kde.org/plasma/breeze-gtk/-/compare/v5.27.3...v5.27.4?from_project_id=1494&straight=false

**Comment by Pointedstick** [comment] 2023-04-07 15:37
Indeed, this is a regression in breeze-gtk 5.27.4; see https://bugs.kde.org/show_bug.cgi?id=468203. A fix is in progress.

**Closed by Pointedstick** 2023-04-07 15:37 UTC
